blueprints/qa.py
from flask import Blueprint, render_template, request, g, redirect, url_for
from .forms import QuestionForm, AnswerForm, PopQuestionForm, RockQuestionForm, PopAnswerForm, RockAnswerForm
from models import QuestionModel, AnswerModel, PopQuestionModel, RockQuestionModel, PopAnswerModel, RockAnswerModel
from exts import db
from decorators import login_required

bp = Blueprint("qa", __name__, url_prefix="/")


@bp.route("/")
def index():
    # return "这是首页"
    return render_template("index.html")


@bp.route("/user-profile", methods=['GET', 'POST'])
def user_profile():
    if request.method == 'GET':
        questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
        popquestions = PopQuestionModel.query.order_by(PopQuestionModel.create_time.desc()).all()
        rockquestions = RockQuestionModel.query.order_by(RockQuestionModel.create_time.desc()).all()
        return render_template("user-profile.html", questions=questions, popquestions=popquestions, rockquestions=rockquestions)
    else:
        print("历史记录失败")
        return redirect(url_for("qa.user_profile"))


@bp.route("/chat", methods=['GET', 'POST'])
@login_required
def publish_qa():
    if not g.user:
        return redirect(url_for("auth.signIn"))
    if request.method == 'GET':
        # 当数据很多时，就需要采用分页
        questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
        return render_template("chat.html", questions=questions)
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            # todo:跳转到这篇的详情页
            return redirect(url_for("qa.publish_qa"))
        else:
            print(form.errors)
            return redirect(url_for("qa.publish_qa"))


@bp.route("/pop-chat", methods=['GET', 'POST'])
@login_required
def publish_qa_pop():
    if not g.user:
        return redirect(url_for("auth.signIn"))
    if request.method == 'GET':
        popquestions = PopQuestionModel.query.order_by(PopQuestionModel.create_time.desc()).all()
        return render_template("pop-chat.html", popquestions=popquestions)
    else:
        form = PopQuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = PopQuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            # todo:跳转到这篇的详情页
            return redirect('/pop-chat')
            # return redirect(url_for("qa.publish_qa_pop"))
        else:
            print(form.errors)
            return redirect(url_for("qa.publish_qa_pop"))


@bp.route("/rock-chat", methods=['GET', 'POST'])
@login_required
def publish_qa_rock():
    if not g.user:
        return redirect(url_for("auth.signIn"))
    if request.method == 'GET':
        rockquestions = RockQuestionModel.query.order_by(RockQuestionModel.create_time.desc()).all()
        return render_template("rock-chat.html", rockquestions=rockquestions)
    else:
        form = RockQuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = RockQuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            # todo:跳转到这篇的详情页
            return redirect("/rock-chat")
        else:
            print(form.errors)
            return redirect(url_for("qa.publish_qa_rock"))


@bp.route("/detail/<qa_id>")
def qa_detail(qa_id):
    question = QuestionModel.query.get(qa_id)
    return render_template("detail.html", question=question)


@bp.route("/detail_pop/<qa_id>")
def qa_detail_pop(qa_id):
    question = PopQuestionModel.query.get(qa_id)
    return render_template("detail-pop.html", question=question)


@bp.route("/detail_rock/<qa_id>")
def qa_detail_rock(qa_id):
    question = RockQuestionModel.query.get(qa_id)
    return render_template("detail-rock.html", question=question)


@bp.route("/answer", methods=['POST'])
@login_required
def public_answer():
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        question_id = form.question_id.data
        answer = AnswerModel(content=content, question_id=question_id, author_id=g.user.id)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for("qa.qa_detail", qa_id=question_id))
    else:
        print(form.errors)
        return redirect(url_for("qa.qa_detail", qa_id=request.form.get("question_id")))


@bp.route("/popanswer", methods=['POST'])
@login_required
def public_answer_pop():
    form = PopAnswerForm(request.form)
    if form.validate():
        content = form.content.data
        question_id = form.question_id.data
        answer = PopAnswerModel(content=content, question_id=question_id, author_id=g.user.id)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for("qa.qa_detail_pop", qa_id=question_id))
    else:
        print(form.errors)
        return redirect(url_for("qa.qa_detail_pop", qa_id=request.form.get("question_id")))


@bp.route("/rockanswer", methods=['POST'])
@login_required
def public_answer_rock():
    form = RockAnswerForm(request.form)
    if form.validate():
        content = form.content.data
        question_id = form.question_id.data
        answer = RockAnswerModel(content=content, question_id=question_id, author_id=g.user.id)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for("qa.qa_detail_rock", qa_id=question_id))
    else:
        print(form.errors)
        return redirect(url_for("qa.qa_detail_rock", qa_id=request.form.get("question_id")))


@bp.route("/search")
def search():
      # 查询方式：
      # /search?q=flask
      # /search/<q>
      # post, request.form
      q = request.args.get("q")
      questions = QuestionModel.query.filter(QuestionModel.title.contains(q)).all()
      return render_template("chat.html", questions=questions)


@bp.route("/search_pop")
def search_pop():
      # 查询方式：
      # /search?q=flask
      # /search/<q>
      # post, request.form
      q = request.args.get("q")
      popquestions = PopQuestionModel.query.filter(PopQuestionModel.title.contains(q)).all()
      return render_template("pop-chat.html", popquestions=popquestions)


@bp.route("/search_rock")
def search_rock():
      # 查询方式：
      # /search?q=flask
      # /search/<q>
      # post, request.form
      q = request.args.get("q")
      rockquestions = RockQuestionModel.query.filter(RockQuestionModel.title.contains(q)).all()
      return render_template("rock-chat.html", rockquestions=rockquestions)


@bp.route("/delete_zhuti", methods=['POST'])
def delete_zhuti():
    question_id = request.form.get("question_id")
    zhuti1 = QuestionModel.query.filter(QuestionModel.id == question_id).first()
    db.session.delete(zhuti1)
    db.session.commit()
    # return render_template("user-profile.html")  错误
    return redirect("/user-profile")


@bp.route("/delete_pop", methods=['POST'])
def delete_pop():
    question_id = request.form.get("question_id")
    pop1 = PopQuestionModel.query.filter(PopQuestionModel.id == question_id).first()
    db.session.delete(pop1)
    db.session.commit()
    # return render_template("user-profile.html")  错误
    return redirect("/user-profile")


@bp.route("/delete_rock", methods=['POST'])
def delete_rock():
    question_id = request.form.get("question_id")
    rock1 = RockQuestionModel.query.filter(RockQuestionModel.id == question_id).first()
    db.session.delete(rock1)
    db.session.commit()
    # return render_template("user-profile.html")  错误
    return redirect("/user-profile")





# url传参
# 邮件发送（验证码）
# ajax
# orm数据库
# JinJa2模板
# cookie和session原理
# 搜索
# ......

templates/chat.html
{% extends "base.html" %}
{% block div %}
<div class="content">
    <div class="breadcrumb-wrapper breadcrumb-contacts">
  <div>
    <h1>主题曲音乐论坛热议</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb p-0">
            <li class="breadcrumb-item">
            </li>
            <li class="breadcrumb-item">
              论坛热议
            </li>
          </ol>
        </nav>
</div>
  </div>
<div class="card card-default mb-0">
  <div class="row bg-white no-gutters chat">
    <div class="col-lg-6 col-xl-7">
      <!-- Chat Left Side -->
      <div class="chat-left-side">

        <form class="chat-search" method="get" action="{{ url_for('qa.search') }}">
          <input type="search" class="form-control" placeholder="请输入关键字搜索" aria-label="Search" name="q">
        </form>

        <ul class="list-unstyled border-top mb-0" id="chat-left-content" data-simplebar>
         {% for question in questions %}
          <li>
            <a href="{{ url_for('qa.qa_detail',qa_id=question.id)}}" class="media media-message">
            <div class="position-relative mr-3">
               {% if question.author_id == 2 %}
              <img class="rounded-circle" src="{{url_for('static', filename='img/user/u3.jpg')}}" alt="Image">
              {% elif question.author_id == 3 %}
              <img class="rounded-circle" src="{{url_for('static', filename='img/user/u8.jpg')}}" alt="Image">
              {% else %}
              <img class="rounded-circle" src="{{url_for('static', filename='img/user/u1.jpg')}}" alt="Image">
              {% endif %}
              <span class="status away"></span>
            </div>
            <div class="media-body d-flex justify-content-between">
              <div class="message-contents">
              <h5 class="font-weight-bold">{{ question.title }}</h5>
              <p class=" last-msg">{{ question.content }}</p>
              </div>
              <span class="date">
                <span class="question-author">{{ question.author.username}}</span>
                <span class="question-time">{{ question.create_time}}</span>
              </span>
            </div>
            </a>
          </li>
          {% endfor %}

        </ul>
      </div>

    </div>
    <div class="col-lg-5 col-xl-5 ">
      <!-- Chats -->
      <div class="chat-right-side">
        <div class="media media-chat align-items-center mb-0 media-chat-header" href="#">
           {% if user.id == 2 %}
          <img class="rounded-circle mr-3" src="{{ url_for('static', filename='img/user/u3.jpg')}}" alt="Image" />
           {% elif user.id == 3 %}
          <img class="rounded-circle mr-3" src="{{ url_for('static', filename='img/user/u8.jpg')}}" alt="Image">
           {% else %}
          <img class="rounded-circle mr-3" src="{{ url_for('static', filename='img/user/u7.jpg')}}" alt="Image">
          {% endif %}
          <div class="media-body w-100">
            <div class="d-flex justify-content-between align-items-center">
              <h3 class="heading-title mb-0"><a href="#">发布点评</a></h3>
<!--              <div class="dropdown">-->
<!--                <a class="dropdown-toggle icon-burger-mini" href="#" role="button" id="dropdownMenuLink"-->
<!--                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">-->
<!--                </a>-->
<!--                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">-->
<!--                  <a class="dropdown-item" href="user-profile.html">Profile</a>-->
<!--                  <a class="dropdown-item" href="index.html">Logout</a>-->
<!--                </div>-->
<!--              </div>-->
            </div>
          </div>
        </div>

        <div class="chat-right-content" id="chat-right-content" data-simplebar>
        <form method="post" >
          <div class="form-group">
            <input type="text" name="title" class="form-control " placeholder="请输入标题">
          </div>
          <div class="form-group">
            <textarea name="content" class="form-control" rows="9" placeholder="请输入内容"></textarea>
          </div>
          <div class="form-group">
            <button class="btn btn-primary">发布</button>
          </div>
        </form>
        </div>


      </div>

    </div>
  </div>
</div>





      </div> <!-- End Content -->
{% endblock %}

templates/detail-pop.html
{% extends "base.html" %}
{% block div %}
 <div class="content">
      <a href="/pop-chat">
       <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
</svg>
    <i class="bi bi-arrow-left-short"></i>
     </a>
<div class="rounded border bg-white px-5">
	<div class="row ">
<!--    <div class="row" style="margin-top: 20px;">-->
      <div class="col"></div>
      <div class="col-10" style="background-color: #fff;padding: 10px;">
        <h3 class="page-title text-center mb-0 font-weight-bold"  style="margin-top: 20px;color:black;">{{ question.title }}</h3>
        <p class="question-info text-center" style="margin-top: 10px;">
          <span>发布人：{{ question.author.username }}</span>
          <span>时间： {{ question.create_time }}</span>
        </p>
        <hr>
        <p class="question-content" style="color:black;">{{ question.content }}</p>
        <hr>
        <!--            要使用popanswers和models.py中的关系的backref=popanswers保持一致-->
        <h4 class="comment-group-title" style="margin-bottom: 10px;color:black;">评论({{ question.popanswers|length}}): </h4>
        <form action="{{ url_for('qa.public_answer_pop')}}" method="post">
          <div class="form-group">
            <input type="text" placeholder="请填写评论" name="content" class="form-control">
            <input type="hidden" name="question_id" value="{{ question.id }}">
          </div>
          <div class="form-group " style="text-align: right;">
            <button class="btn btn-primary">评论</button>
          </div>
        </form>
          <ul class="comment-group">
            <!--            要使用rockanswers和models.py中的关系的backref=popanswers保持一致-->
          {% for answer in question.popanswers %}
          <li>
            <div class="media media-message">
              <div class="position-relative mr-3">
                {% if answer.author_id == 2 %}
                <img src="{{ url_for('static', filename='img/user/u3.jpg')}}" class="img-circle" alt="User Image" />
                {% elif answer.author_id == 3 %}
                <img src="{{ url_for('static', filename='img/user/u8.jpg')}}" class="img-circle" alt="User Image" />
                {% else %}
                <img src="{{ url_for('static', filename='img/user/u7.jpg')}}" class="img-circle" alt="User Image" />
                {% endif %}
              </div>
              <div class="media-body d-flex justify-content-between">
                <div class="message-contents">
<!--                  <span class="username">{{ answer.author.username}}</span>-->
                   <h4 class="title">{{ answer.author.username}}</h4>
<!--                   <p class="comment-content">{{ answer.content }}</p>-->
                  <p class="last-msg">{{ answer.content }}</p>
                </div>
                <span class="date">{{ answer.create_time}}</span>
              </div>


            </div>

          </li>
          {% endfor %}
        </ul>
<!--      </div>-->
    </div>
<div class="col"></div>
	</div>
</div>
      </div> <!-- End Content -->
{% endblock %}

templates/detail-rock.html
{% extends "base.html" %}
{% block div %}
 <div class="content">
   <a href="/rock-chat">
       <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
</svg>
    <i class="bi bi-arrow-left-short"></i>
     </a>
<div class="rounded border bg-white px-5">
	<div class="row ">
<!--    <div class="row" style="margin-top: 20px;">-->
      <div class="col"></div>
      <div class="col-10" style="background-color: #fff;padding: 10px;">
        <h3 class="page-title text-center mb-0 font-weight-bold"  style="margin-top: 20px;color:black;">{{ question.title }}</h3>
        <p class="question-info text-center" style="margin-top: 10px;">
          <span>发布人：{{ question.author.username }}</span>
          <span>时间： {{ question.create_time }}</span>
        </p>
        <hr>
        <p class="question-content" style="color:black;">{{ question.content }}</p>
        <hr>
        <!--            要使用rockanswers和models.py中的关系的backref=rockanswers保持一致-->
        <h4 class="comment-group-title" style="margin-bottom: 10px;color:black;">评论({{ question.rockanswers|length}}): </h4>
        <form action="{{ url_for('qa.public_answer_rock')}}" method="post">
          <div class="form-group">
            <input type="text" placeholder="请填写评论" name="content" class="form-control">
            <input type="hidden" name="question_id" value="{{ question.id }}">
          </div>
          <div class="form-group " style="text-align: right;">
            <button class="btn btn-primary">评论</button>
          </div>
        </form>
          <ul class="comment-group">
<!--            要使用rockanswers和models.py中的关系的backref=rockanswers保持一致-->
          {% for answer in question.rockanswers %}
          <li>
            <div class="media media-message">
              <div class="position-relative mr-3">
                {% if answer.author_id == 2 %}
                <img src="{{ url_for('static', filename='img/user/u3.jpg')}}" class="img-circle" alt="User Image" />
                {% elif answer.author_id == 3 %}
                <img src="{{ url_for('static', filename='img/user/u8.jpg')}}" class="img-circle" alt="User Image" />
                {% else %}
                <img src="{{ url_for('static', filename='img/user/u7.jpg')}}" class="img-circle" alt="User Image" />
                {% endif %}
              </div>
              <div class="media-body d-flex justify-content-between">
                <div class="message-contents">
<!--                  <span class="username">{{ answer.author.username}}</span>-->
                   <h4 class="title">{{ answer.author.username}}</h4>
<!--                   <p class="comment-content">{{ answer.content }}</p>-->
                  <p class="last-msg">{{ answer.content }}</p>
                </div>
                <span class="date">{{ answer.create_time}}</span>
              </div>


            </div>

          </li>
          {% endfor %}
        </ul>
<!--      </div>-->
    </div>
<div class="col"></div>
	</div>
</div>
      </div> <!-- End Content -->
{% endblock %}

templates/detail.html
{% extends "base.html" %}
{% block div %}
 <div class="content">
      <a href="/chat">
       <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
</svg>
    <i class="bi bi-arrow-left-short"></i>
     </a>
<div class="rounded border bg-white px-5">
	<div class="row ">
<!--    <div class="row" style="margin-top: 20px;">-->
      <div class="col"></div>
      <div class="col-10" style="background-color: #fff;padding: 10px;">
        <h3 class="page-title text-center mb-0 font-weight-bold"  style="margin-top: 20px;color:black;">{{ question.title }}</h3>
        <p class="question-info text-center" style="margin-top: 10px;">
          <span>发布人：{{ question.author.username }}</span>
          <span>时间： {{ question.create_time }}</span>
        </p>
        <hr>
        <p class="question-content" style="color:black;">{{ question.content }}</p>
        <hr>
        <h4 class="comment-group-title" style="margin-bottom: 10px;color:black;">评论({{ question.answers|length}}): </h4>
        <form action="{{ url_for('qa.public_answer')}}" method="post">
          <div class="form-group">
            <input type="text" placeholder="请填写评论" name="content" class="form-control">
            <input type="hidden" name="question_id" value="{{ question.id }}">
          </div>
          <div class="form-group " style="text-align: right;">
            <button class="btn btn-primary">评论</button>
          </div>
        </form>
          <ul class="comment-group">
          {% for answer in question.answers %}
          <li>
            <div class="media media-message">
              <div class="position-relative mr-3">
                {% if answer.author_id == 2 %}
                <img src="{{ url_for('static', filename='img/user/u3.jpg')}}" class="img-circle" alt="User Image" />
                {% elif answer.author_id == 3 %}
                <img src="{{ url_for('static', filename='img/user/u8.jpg')}}" class="img-circle" alt="User Image" />
                {% else %}
                <img src="{{ url_for('static', filename='img/user/u7.jpg')}}" class="img-circle" alt="User Image" />
                {% endif %}
              </div>
              <div class="media-body d-flex justify-content-between">
                <div class="message-contents">
<!--                  <span class="username">{{ answer.author.username}}</span>-->
                   <h4 class="title">{{ answer.author.username}}</h4>
<!--                   <p class="comment-content">{{ answer.content }}</p>-->
                  <p class="last-msg">{{ answer.content }}</p>
                </div>
                <span class="date">{{ answer.create_time}}</span>
              </div>


            </div>

          </li>
          {% endfor %}
        </ul>
<!--      </div>-->
    </div>
<div class="col"></div>
	</div>
</div>
      </div> <!-- End Content -->
{% endblock %}

templates/pop-chat.html
{% extends "base.html" %}
{% block div %}
<div class="content">
      <div class="breadcrumb-wrapper breadcrumb-contacts">
  <div>
    <h1>流行音乐论坛热议</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb p-0">
            <li class="breadcrumb-item">
            </li>
            <li class="breadcrumb-item">
              论坛热议
            </li>
          </ol>
        </nav>
</div>
  </div>
<div class="card card-default mb-0">
  <div class="row bg-white no-gutters chat">
    <div class="col-lg-6 col-xl-7">
      <!-- Chat Left Side -->
      <div class="chat-left-side">

        <form class="chat-search" method="get" action="{{ url_for('qa.search_pop') }}">
          <input type="search" class="form-control" placeholder="请输入关键字搜索" aria-label="Search" name="q">
        </form>

        <ul class="list-unstyled border-top mb-0" id="chat-left-content" data-simplebar>
         {% for question in popquestions %}
          <li>
            <a href="{{ url_for('qa.qa_detail_pop',qa_id=question.id)}}" class="media media-message">
            <div class="position-relative mr-3">
               {% if question.author_id == 2 %}
              <img class="rounded-circle" src="{{url_for('static', filename='img/user/u3.jpg')}}" alt="Image">
              {% elif question.author_id == 3 %}
              <img class="rounded-circle" src="{{url_for('static', filename='img/user/u8.jpg')}}" alt="Image">
              {% else %}
              <img class="rounded-circle" src="{{url_for('static', filename='img/user/u7.jpg')}}" alt="Image">
              {% endif %}
              <span class="status away"></span>
            </div>
            <div class="media-body d-flex justify-content-between">
              <div class="message-contents">
              <h5 class="font-weight-bold">{{ question.title }}</h5>
              <p class=" last-msg">{{ question.content }}</p>
              </div>
              <span class="date">
                <span class="question-author">{{ question.author.username}}</span>
                <span class="question-time">{{ question.create_time}}</span>
              </span>
            </div>
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>

    </div>
    <div class="col-lg-5 col-xl-5 ">
      <!-- Chats -->
      <div class="chat-right-side">
        <div class="media media-chat align-items-center mb-0 media-chat-header" href="#">
           {% if user.id == 2 %}
          <img class="rounded-circle mr-3" src="{{ url_for('static', filename='img/user/u3.jpg')}}" alt="Image">
           {% elif user.id == 3 %}
          <img class="rounded-circle mr-3" src="{{ url_for('static', filename='img/user/u8.jpg')}}" alt="Image">
          {% else %}
          <img class="rounded-circle mr-3" src="{{ url_for('static', filename='img/user/u7.jpg')}}" alt="Image">
          {% endif %}
          <div class="media-body w-100">
            <div class="d-flex justify-content-between align-items-center">
              <h3 class="heading-title mb-0"><a href="#">发布点评</a></h3>
            </div>
          </div>
        </div>

        <div class="chat-right-content" id="chat-right-content" data-simplebar>
        <form method="post" >
          <div class="form-group">
            <input type="text" name="title" class="form-control " placeholder="请输入标题">
          </div>
          <div class="form-group">
            <textarea name="content" class="form-control" rows="9" placeholder="请输入内容"></textarea>
          </div>
          <div class="form-group">
            <button class="btn btn-primary">发布</button>
          </div>
        </form>
        </div>


      </div>

    </div>
  </div>
</div>
     </div> <!-- End Content -->
{% endblock %}

templates/rock-chat.html
{% extends "base.html" %}
{% block div %}
<div class="content">
  <div class="breadcrumb-wrapper breadcrumb-contacts">
  <div>

    <h1>摇滚音乐论坛热议</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb p-0">
            <li class="breadcrumb-item">
            </li>
            <li class="breadcrumb-item">
              论坛热议
            </li>
          </ol>
        </nav>
</div>
  </div>
<div class="card card-default mb-0">
  <div class="row bg-white no-gutters chat">
    <div class="col-lg-6 col-xl-7">
      <!-- Chat Left Side -->
      <div class="chat-left-side">

        <form class="chat-search" method="get" action="{{ url_for('qa.search_rock') }}">
          <input type="search" class="form-control" placeholder="请输入关键字搜索" aria-label="Search" name="q">
        </form>

        <ul class="list-unstyled border-top mb-0" id="chat-left-content" data-simplebar>
         {% for question in rockquestions %}
          <li>
            <a href="{{ url_for('qa.qa_detail_rock',qa_id=question.id)}}" class="media media-message">
            <div class="position-relative mr-3">
              {% if question.author_id == 2 %}
              <img class="rounded-circle" src="{{url_for('static', filename='img/user/u3.jpg')}}" alt="Image">
              {% elif question.author_id == 3 %}
              <img class="rounded-circle" src="{{url_for('static', filename='img/user/u8.jpg')}}" alt="Image">
              {% else %}
              <img class="rounded-circle" src="{{url_for('static', filename='img/user/u7.jpg')}}" alt="Image">
              {% endif %}
              <span class="status away"></span>
            </div>
            <div class="media-body d-flex justify-content-between">
              <div class="message-contents">
              <h5 class="font-weight-bold">{{ question.title }}</h5>
              <p class=" last-msg">{{ question.content }}</p>
              </div>
              <span class="date">
                <span class="question-author">{{ question.author.username}}</span>
                <span class="question-time">{{ question.create_time}}</span>
              </span>
            </div>
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>

    </div>
    <div class="col-lg-5 col-xl-5 ">
      <!-- Chats -->
      <div class="chat-right-side">
        <div class="media media-chat align-items-center mb-0 media-chat-header" href="#">
          {% if user.id == 2 %}
          <img class="rounded-circle mr-3" src="{{ url_for('static', filename='img/user/u3.jpg')}}" alt="Image">
          {% elif user.id == 3 %}
          <img class="rounded-circle mr-3" src="{{ url_for('static', filename='img/user/u8.jpg')}}" alt="Image">
          {% else %}
          <img class="rounded-circle mr-3" src="{{ url_for('static', filename='img/user/u7.jpg')}}" alt="Image">
          {% endif %}
          <div class="media-body w-100">
            <div class="d-flex justify-content-between align-items-center">
              <h3 class="heading-title mb-0"><a href="#">发布点评</a></h3>
            </div>
          </div>
        </div>

        <div class="chat-right-content" id="chat-right-content" data-simplebar>
        <form method="post" >
          <div class="form-group">
            <input type="text" name="title" class="form-control " placeholder="请输入标题">
          </div>
          <div class="form-group">
            <textarea name="content" class="form-control" rows="9" placeholder="请输入内容"></textarea>
          </div>
          <div class="form-group">
            <button class="btn btn-primary">发布</button>
          </div>
        </form>
        </div>


      </div>

    </div>
  </div>
</div>
     </div> <!-- End Content -->
{% endblock %}